version: '3.8'

services:
  # PostgreSQL Database for FHIR
  fhir-db:
    image: postgres:14
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: hapi
      POSTGRES_PASSWORD: hapi
    volumes:
      - fhir-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # HAPI FHIR Server
  fhir-server:
    image: hapiproject/hapi:latest
    environment:
      spring.datasource.url: jdbc:postgresql://fhir-db:5432/hapi
      spring.datasource.username: hapi
      spring.datasource.password: hapi
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hapi.fhir.enable_repository_validating_interceptor: 'false'
    ports:
      - "8081:8080"
    depends_on:
      - fhir-db

  # Python MCP Server
  mcp-server:
    build: ./mcp-server-python
    environment:
      FHIR_SERVER_URL: http://fhir-server:8080/fhir
    env_file:
      - .env
    depends_on:
      - fhir-server

  # Python Backend API
  backend-api:
    build: ./backend-api-python
    ports:
      - "3001:3001"
    environment:
      MCP_SERVER_PATH: /app/mcp_server/main.py
      FHIR_SERVER_URL: http://fhir-server:8080/fhir
      CORS_ORIGIN: http://localhost:3000
    env_file:
      - .env
    depends_on:
      - mcp-server
      - fhir-server
    volumes:
      - ./mcp-server-python:/app/mcp_server:ro

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend-api

volumes:
  fhir-data: