
services:
  # External FHIR Server (Spark FHIR) - using external server at 10.201.205.101:8007
  # No local FHIR server or database needed - commenting out for reference
  #
  # fhir-db:
  #   image: postgres:14
  #   ...
  #
  # fhir-server:
  #   image: hapiproject/hapi:latest
  #   ...

  # Python MCP Server
  mcp-server:
    build: ./mcp-server-python
    container_name: emr-mcp-server
    env_file:
      - .env
    environment:
      # point at the external Spark FHIR server
      FHIR_SERVER_URL: http://10.201.205.101:8007/
    networks:
      - emr-network

  # Python Backend API
  backend-api:
    build: ./backend-api-python
    container_name: emr-backend-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      # point at the in-Docker MCP server & external FHIR server
      MCP_SERVER_PATH: /app/mcp_server/main.py
      FHIR_SERVER_URL: http://10.201.205.101:8007/
      CORS_ORIGIN:    http://localhost:3000
    depends_on:
      - mcp-server
    volumes:
      - ./mcp-server-python:/app/mcp_server:ro
    networks:
      - emr-network

  # React Frontend
  frontend:
    build: ./frontend
    container_name: emr-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      # point at the in-Docker backend
      VITE_API_URL: http://backend-api:3001
    depends_on:
      - backend-api
    networks:
      - emr-network

  # Adminer - Postgres GUI (disabled since using external FHIR server)
  # adminer:
  #   image: adminer
  #   container_name: emr-adminer
  #   ports:
  #     - "8082:8080"
  #   depends_on:
  #     - fhir-db
  #   environment:
  #     ADMINER_DEFAULT_SERVER: fhir-db
  #   networks:
  #     - emr-network

# volumes:
  # fhir-data: # Not needed since using external FHIR server

networks:
  emr-network:
    driver: bridge
