version: '3.8'

services:
  # PostgreSQL for FHIR Server
  fhir-db:
    image: postgres:15
    container_name: emr-fhir-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_USER=hapiuser
      - POSTGRES_PASSWORD=hapipass
    volumes:
      - fhir-data:/var/lib/postgresql/data
    networks:
      - emr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hapiuser -d hapi"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FHIR Server
  fhir-server:
    image: hapiproject/hapi:latest
    container_name: emr-fhir-server
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://fhir-db:5432/hapi
      - spring.datasource.username=hapiuser
      - spring.datasource.password=hapipass
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - hapi.fhir.server_address=http://localhost:8081/fhir
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.max-active=15
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.cors.allowed_origin=*
    depends_on:
      fhir-db:
        condition: service_healthy
    networks:
      - emr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API (development mode - comment out for local dev)
  backend-api:
    build: ./backend-api
    container_name: emr-backend-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FHIR_SERVER_URL=http://fhir-server:8080/fhir
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - fhir-server
    networks:
      - emr-network
    restart: unless-stopped

  # Frontend (development mode - comment out for local dev)
  frontend:
    build: ./frontend
    container_name: emr-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend-api
    networks:
      - emr-network
    restart: unless-stopped

volumes:
  fhir-data:

networks:
  emr-network:
    driver: bridge